pulsar:
  service-url: pulsar://localhost:6650
dubbo:
  application:
    name: ${application.name}
  registry:
    address: nacos://127.0.0.1:8848
    parameters:
      namespace: c9dfc362-34df-4778-820c-9cacfeb72274